development:
  adapter: postgresql
  encoding: unicode
  database: api_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: api_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: api_production
  pool: 5